from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# Consistent naming convention for Alembic migrations.
# This prevents random constraint names generated by PostgreSQL.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(
    naming_convention=NAMING_CONVENTION
)


class Base(DeclarativeBase):
    """
    Parent of every SQLAlchemy model.
    """

    metadata = metadata


# Import all models here so that they register on Base.metadata for Alembic autogenerate
from app.db.models.user import User
from app.db.models.conversation import ChatConversation, ChatMessage
from app.db.models.memory import MemoryEntry
from app.models.platform import Platform
from app.models.social_account import SocialAccount
from app.models.conversation import Conversation
from app.models.conversation_participant import ConversationParticipant
from app.models.message import Message
from app.models.attachment import Attachment