"""add_reply_mode_to_conversation

Revision ID: cfde88b88426
Revises: 1a5e70b8e766
Create Date: 2026-07-12 14:40:29.716164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfde88b88426'
down_revision: Union[str, Sequence[str], None] = '1a5e70b8e766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('reply_mode', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'reply_mode')
    # ### end Alembic commands ###
